# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to NuGet

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release ./src/DeepSeek.NET/DeepSeek.NET.csproj

            - name: Pack
              run: dotnet pack --configuration Release ./src/DeepSeek.NET/DeepSeek.NET.csproj --output ./nupkg

            - name: Publish to NuGet
              run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json